---
title: "RT_model"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r}
# Getting data
game_info <- read_csv("../data2/game_info_df.csv")
```

```{r}
win_matrix <- game_info %>%
                filter(season == 20162017) %>%
                mutate(win_team = if_else(home_score > away_score, 
                                          home_team, 
                                          away_team),
                lose_team = if_else(win_team == home_team, 
                                    away_team, 
                                    home_team)) %>%
                select(win_team, lose_team)

team_names <- unique(win_matrix$win_team)

# rows of W are the winning teams
W <- matrix(rep(0, length(team_names)^2), ncol = length(team_names))
rownames(W) <- team_names
colnames(W) <- team_names

apply(win_matrix, 1, function(x){
  # using the <<- to access the W in the outer scope
  W[x[["win_team"]], x[["lose_team"]]] <<- W[x[["win_team"]], x[["lose_team"]]] + 1
  return()
})

```

```{r}
tau <- vector(length=nrow(W))
for(i in 1:nrow(W)){
  tau[i] <- sum(W[i, ])/(sum(W[, i]) + sum(W[i, ]))
}
tau[1] <- 1

for(iter in 1:niter){
  for(k in 2:length(tau)){
    tau_k.1 <- 0
    for(i in 1:nrow(W)){
      tau_k.1 <- tau_k.1 + W[k,i]
    }
    
    tau_k.2 <- 0
    for(i in 1:nrow(W)){
      tau_k.2 <- tau_k.2 + ((W[k,i] + W[i,k])/(tau[k] + tau[i]))  
    }
    tau[k] <- tau_k.1/tau_k.2
  }
}

as_tibble(cbind(team_names, tau)) %>% arrange(desc(tau))
```










