---
title: "test"
author: "Yatharth Khattar"
date: "20/02/2021"
output: html_document
---

```{r message=FALSE}
library(tidyverse)
library(caret)
library(data.table)
library(dtplyr)
pbp_data <- read_csv("../data/pbp_base.csv")
sub_pbp <- pbp_data %>% filter(season == 20182019)
```

```{r}
old_names1 <- c(paste0("away_on_", 1:7), paste0("home_on_", 1:7),
              "home_team", "away_team", "shift_start", "shift_end",
              "home_team_shots_per_60", "game_id")
new_names1 <- c(paste0("def_player_", 1:7), paste0("off_player_", 1:7),
              "home_team", "away_team", "shift_start", "shift_end",
              "shots_per_60", "game_id")

old_names2 <- c(paste0("away_on_", 1:7), paste0("home_on_", 1:7),
              "home_team", "away_team", "shift_start", "shift_end",
              "away_team_shots_per_60", "game_id")
new_names2 <- c(paste0("off_player_", 1:7), paste0("def_player_", 1:7),
              "home_team", "away_team", "shift_start", "shift_end",
                "shots_per_60", "game_id")

get_rapm_data_per_game <- function(pbp){
    # splitting the data so that each row is a single shift where no on leaves the ice
  shift_data <- pbp %>% filter(event_type == "CHANGE") %>% 
                mutate(is_home_team_event = if_else(event_team == home_team, 
                                                    1, 0)) %>% 
                select(game_id, game_seconds, event_team, 
                       paste0("away_on_", 1:7), paste0("home_on_", 1:7), 
                       is_home_team_event, home_goalie, away_goalie, 
                       home_team, away_team) %>% 
                group_by(game_seconds) %>% 
                slice(n()) %>% 
                ungroup(game_seconds) %>% 
                mutate(shift_start = game_seconds,
                       shift_end = lead(game_seconds)) %>%   
                head(-1) %>% 
                mutate(across(c(home_on_1:home_on_7, away_on_1:away_on_7), 
                              function(x){
                                          ifelse(x==home_goalie, NA, 
                                          ifelse(x==away_goalie, NA, x))})) 

  shift_times <- shift_data[c("shift_start", "shift_end")]
  
  # Getting shot data
  shot_type <- c("BLOCK", "GOAL", "MISS", "SHOT")
  shot_data  <- pbp %>% filter(event_type %in% shot_type) %>% 
                  dplyr::select(game_seconds, event_team, event_type, home_team,
                                away_team) %>% 
                  mutate(is_home_team = if_else(event_team == home_team, 1, 0))
  
  # Combinding shot data with shift data
  home_team_shot_times <- shot_data %>% 
                          filter(is_home_team == 1) %>% 
                          pull(game_seconds)
    
  away_team_shot_times <- shot_data %>% 
                          filter(is_home_team == 0) %>% 
                          pull(game_seconds)
  
  final_shift_data <- apply(shift_times, 1, function(x){
    home_team_shot <- sum(x[["shift_start"]] <= home_team_shot_times &
                          home_team_shot_times < x[["shift_end"]])
    away_team_shot <- sum(x[["shift_start"]] <= away_team_shot_times &
                          away_team_shot_times < x[["shift_end"]])
    return(tibble(home_team_shots = home_team_shot, 
                  away_team_shots = away_team_shot))
  }) %>% bind_rows(.) %>% bind_cols(., shift_data) %>% 
    mutate(home_team_shots_per_60 = (home_team_shots/(shift_end - shift_start))*3600,
           away_team_shots_per_60 = (away_team_shots/(shift_end - shift_start))*3600)

  # Double each row and make columns for offensive players and defensive players
  # and also create a dummy variable that is 1 if home team == offensive team
  home_team_data <- final_shift_data %>%
    dplyr::select(all_of(old_names1)) %>%
    rename_with(~ new_names1[which(old_names1 == .x)], .cols = old_names1) %>% 
    mutate(off_is_home = 1)
  
  away_team_data <- final_shift_data %>% 
    dplyr::select(all_of(old_names2)) %>%
    rename_with(~ new_names2[which(old_names2 == .x)], .cols = old_names2) %>% 
    mutate(off_is_home = 0)
  
  bind_rows(home_team_data, away_team_data) %>% mutate(id=1:n()) %>%
    arrange(shift_start)
}
# 
# gid <- 2017020265
# v <- get_rapm_data_per_game(pbp_data %>% filter(game_id == gid))

sub_pbp2 <- lazy_dt(sub_pbp)

d <- sub_pbp2 %>% group_by(game_id) %>%
     group_map(function(x){get_rapm_data_per_game(x)}, keep=TRUE) %>% 
     as_tibble()

# d <- sub_pbp %>% group_by(game_id) %>% 
#       nest() %>% 
#       mutate(out = purrr::map(., function(x) get_rapm_data_per_game(x))) %>% 
#       unnest(out)
```

```{r}
# Multi hot encoding the player variables
off_dummy <- v %>% dplyr::select(c(paste0("off_player_", 1:7), "id", "game_id")) %>% setDT()
off_dummy <- dcast(setDT(melt(off_dummy,id.vars = c("id", "game_id")))[,ind:=1], id+game_id~value, 
                   value.var = "ind",fill=0) %>%
              as_tibble() %>% dplyr::select(-"NA")

colnames(off_dummy) <- c("id", "game_id", paste0("off_",colnames(off_dummy)[3:length(off_dummy)])) 


def_dummy <- v %>% dplyr::select(c(paste0("def_player_", 1:7), "id", "game_id")) %>% setDT()
def_dummy <- dcast(setDT(melt(def_dummy,id.vars = c("id", "game_id")))[,ind:=1], id+game_id~value, 
                   value.var = "ind",fill=0) %>%
              as_tibble() %>% dplyr::select(-"NA")

colnames(def_dummy) <- c("id", "game_id", paste0("def_",colnames(def_dummy)[3:length(def_dummy)])) 


final_data <- bind_cols(off_dummy %>% dplyr::select(-c("id", "game_id")), def_dummy, 
          v %>% dplyr::select(home_team, away_team, shift_start, 
                              shift_end, shots_per_60,off_is_home,))

final_data
```










